### ISSUE TITLE
Forman-Ricci curvature of a simplicial complex

### ISSUE THREAD

**Issue by oleg-kachan** [ExpectozJJ/GeneralisedFormanRicci#1]
Hello!

Could you please provide mathematics behind the generalization of Forman-Ricci curvature to simplicial complexes?

**Comment by ExpectozJJ** [comment]
The implementation is **still** based on the combinatorial definition of Forman Ricci curvature defined by Robin Forman. This implementation **generalises beyond the simplified version** implemented in saibalmars/GraphRicciCurvature github.

**Comment by oleg-kachan** [comment]
Could you give insight into the usage of incidence and Laplacian matrices for the Forman-Ricci curvature computation?

**Comment by ExpectozJJ** [comment]
To be precise, the Hodge laplacian for every dimension p > 0 can be decomposed into the Bochner laplacian and a matrix with diagonals representing the Forman Ricci Curvature of of p-simplices. The decomposition is a combinatorial version of Bochner-Weitzenböck Decomposition.
